# Generated by Django 5.1.6 on 2025-02-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterBottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=10, unique=True)),
                ("brand", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("size", models.CharField(max_length=100)),
                ("mouthSize", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("currentQuantity", models.IntegerField()),
                (
                    "suppliers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyInventoryApp.supplier",
                    ),
                ),
            ],
        ),
    ]
