# Generated by Django 5.1.5 on 2025-02-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
